version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive
    - vcpkg install boost-test:x64-windows --featurepackages

before_build:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - ls -l

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln
  parallel: true

test_script:
  - ctest -C %configuration% -V

cache:
  c:\tools\vcpkg\installed\